### ISSUE TITLE
[Example] Terms Network

### ISSUE THREAD

**Issue by Yomguithereal** [medialab/graphlib#14]
I created an example [here](https://github.com/medialab/graphlib/blob/master/examples/terms.js) of how one might build a network of expression terms.

**Comment by Yomguithereal** [comment]
While coding it, the following API questions emerged:

1. Should we have `graph.get` for nodes and `graph.getEdge` for edges or `graph.getNode` and `graph.getEdge`. I would vouch for the second option whenever possible since it is easier to understand and has no implicit meaning.
2. `graph.get()` should accept references as well as ids. It enables very concise and readable patterns using `map` and such.
3. Should the graph handle edge weights by itself or let the user do so (this raise other questions about parallel edges etc.)? I would say let the user handle the concept of weight.
4. Should add methods return the graph instance or the created object. If we want to remain consistent with ES6 Set and Map then we should return the graph instance.
5. There are a lot of ways to design the `addEdge` method. We should discuss them.

**Comment by DavidBruant** [comment]
1. second option is more explicit indeed.

In any case, let's list use cases. The answers will follow directly.

**Comment by jacomyma** [comment]
...and above all more consistent. [Consistency](https://www.quora.com/Why-is-consistency-important-in-design) is a rule of thumb for such a lib.

**Comment by Yomguithereal** [comment]
I guess the matter of 1. is solved then :).

**Comment by boogheta** [comment]
Yep for 1

Agree with 2 and 4 as well.

For 3 this can easily become a complex configuration choice. It looks to me like allowing parallel edges and weight handling are two separate features (see for instance a transit network with different transportations means to travel from A to B), although when parallel edges are possible, autoadding weight supposes to have already identified exactly which of the parallel links possible one wants to increase. Maybe if in parallel we suppose the weight of a link is fixed once and for all, we can reduce the choices to "parallel edges", "incremental weighted unique edges" and "non weighted unique edges".
